-- MySQL Workbench Synchronization
-- Model: New Model
-- Version: 1.0
-- Project: CDBase
-- Author: goaluix

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`comic` 
CHANGE COLUMN `name` `name` VARCHAR(45) NOT NULL COMMENT '' ,
CHANGE COLUMN `number` `number` INT(11) NOT NULL COMMENT '' ,
ADD COLUMN `idstory_arc` INT(11) NULL DEFAULT NULL COMMENT '' AFTER `cover_price`,
ADD COLUMN `readed` TINYINT(1) NULL DEFAULT NULL COMMENT '' AFTER `idstory_arc`,
ADD INDEX `idstory_arc_idx` (`idstory_arc` ASC)  COMMENT '';

ALTER TABLE `mydb`.`comic` 
ADD CONSTRAINT `idstory_arc`
  FOREIGN KEY (`idstory_arc`)
  REFERENCES `mydb`.`story_arc` (`idstory_arc`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
